name: Sync

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:

env:
  AWS_REGION: sa-east-1

  ENGINE_URL: https://engine.medici.uy/
  ENGINE_SECRET: ${{ secrets.ENGINE_SECRET }}

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: Swatinem/rust-cache@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Sync
        run: ./target/release/data-sync sync --sync-images-bucket
